mindmap
    )Band(
        {{LF}}
            {{125 kHz}}
                (Access Card)
            {{134.2 kHz}}
                (Animal Id)
                ::icon(fa fa-paw)
        {{HF - 13.56 MHz}}
            (ID Card)
            ::icon(fa-solid fa-id-card)
            (Transports)
            ::icon(fa-solid fa-train-subway)
            (Credit Card)
            ::icon(fa-solid fa-credit-card)


        {{UHF - 433 MHz}}
            (Industry)
            ::icon(fa-solid fa-industry)
            (Military)
            ::icon(fa-solid fa-person-military-rifle)
        
        {{UHF 865 - 928 MHz}}
            (RF EAS)
            ::icon(fa-solid fa-shop-lock)
            (Railroads)
            ::icon(fa-solid fa-train)
            
        {{UHF-SHF 2.45 - 5.8 MHz}}
            (Toll road)
            ::icon(fa-solid fa-car-side)
            (WiFi)
            ::icon(fa-solid fa-wifi)