flowchart TD
    military["Military"]
    railroad["Railroads"]
    payment["Payment"]
    
    appType["Identification Type"] --> item & human & military & railroad & payment
    subgraph item["Item"]
        supplychain["Supplychain and Warehouse"]
        rfeas["RF EAS"]
        rks["Remote Keyless System"]
    end
    subgraph human["Human"]
        transport["Transports"]
        building["Corporate & Building Pass"]
        toll["Tollway & Car Identification"]
        student["Student Card"]
        id["ID Card"]
        otherAccess["Other Access"]
    end

    region[Region] --> EU[Europe] & US[U.S.] & JHT[Japan, Hong Kong, Tawain] & Other
    EU & US --> B
    EU --> V
    JHT --> F

    sec[Needed Security] --> auth(["Needs authentication"]) --> |Yes| high["High Security"]
    auth --> |No| human(["Intended for human identification"])

    human --> |Yes| trust(["You trust each other<br/>OR<br/>A theft couldn't be very harmful"])
    human --> |No<br/>Animal or item identification| low
    trust --> |No| medium["Average Security"]
    trust --> |Yes| low["Low Security"]
    
    range[Range] --> |"By hand"| short["10cm"]
    range --> |"Automatic Gate (e.g car, bicycle)"| long["2m"]
